"""initial schema

Revision ID: 274c8eda9f3c
Revises: 
Create Date: 2026-05-14 15:52:23.178958
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa




revision: str = '274c8eda9f3c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_code'), 'buildings', ['code'], unique=True)
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_faculties_code'), 'faculties', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('ACADEMIC_OFFICE', 'DEPARTMENT', 'SCHEDULER', name='user_role', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_departments_faculty_code')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'number', name='uq_rooms_building_number')
    )
    op.create_index(op.f('ix_rooms_number'), 'rooms', ['number'], unique=False)
    op.create_table('study_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['study_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_study_groups_faculty_code')
    )
    op.create_index(op.f('ix_study_groups_code'), 'study_groups', ['code'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_full_name'), 'teachers', ['full_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_subjects_department_code')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='lesson_plan_status', native_enum=False), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('study_group_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_academic_year'), 'lesson_plans', ['academic_year'], unique=False)
    op.create_table('lesson_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.Enum('LECTURE', 'PRACTICE', 'LAB', 'SEMINAR', 'EXAM', 'CONSULTATION', 'OTHER', name='lesson_type', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lesson_plan_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_plan_id', 'lesson_number', name='uq_lesson_plan_items_plan_number')
    )
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('LESSON', 'DAY_OFF', 'SELF_STUDY', name='schedule_entry_type', native_enum=False), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('week_type', sa.Enum('EVERY', 'ODD', 'EVEN', name='week_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lesson_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_plan_item_id'], ['lesson_plan_items.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_lesson_date'), 'schedule_entries', ['lesson_date'], unique=False)
    op.create_index(op.f('ix_schedule_entries_period_number'), 'schedule_entries', ['period_number'], unique=False)
    op.create_table('schedule_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('REPLACEMENT', 'MOVE', 'CANCELLATION', name='schedule_change_type', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('original_entry_id', sa.Integer(), nullable=False),
    sa.Column('replacement_entry_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['replacement_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_changes_change_type'), 'schedule_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_schedule_changes_effective_date'), 'schedule_changes', ['effective_date'], unique=False)
    op.create_table('schedule_entry_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_entry_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_entry_id', 'study_group_id', name='uq_schedule_entry_groups_entry_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_entry_groups')
    op.drop_index(op.f('ix_schedule_changes_effective_date'), table_name='schedule_changes')
    op.drop_index(op.f('ix_schedule_changes_change_type'), table_name='schedule_changes')
    op.drop_table('schedule_changes')
    op.drop_index(op.f('ix_schedule_entries_period_number'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_lesson_date'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_table('lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plans_academic_year'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_full_name'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_study_groups_code'), table_name='study_groups')
    op.drop_table('study_groups')
    op.drop_index(op.f('ix_rooms_number'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('roles')
    op.drop_index(op.f('ix_faculties_code'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_buildings_code'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###